# Generated by Django 5.1.5 on 2025-01-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('backLog', 'Backlog'), ('toDo', 'Todo'), ('backinProgressLog', 'Inprogress'), ('done', 'Done')], default='toDo', max_length=20, verbose_name='Статус')),
                ('tType', models.CharField(choices=[('bug', 'Bug'), ('feature', 'Feature')], default='bug', max_length=20, verbose_name='Тип')),
                ('creationTime', models.DateTimeField(auto_now_add=True)),
                ('estimatedDuration', models.IntegerField(default=1, verbose_name='Оценочное время')),
            ],
        ),
    ]
