# Generated by Django 5.1.5 on 2025-02-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.IntegerField(blank=True, null=True, verbose_name='Пользователь'),
        ),
    ]
