# Generated by Django 5.1.5 on 2025-02-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_task_priority_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('backLog', 'Backlog'), ('inProgressLog', 'Inprogress'), ('propose', 'Propose'), ('done', 'Done')], default='backLog', max_length=20, verbose_name='Статус'),
        ),
    ]
