# Generated by Django 5.1.5 on 2025-03-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_task_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
