# Generated by Django 5.1.5 on 2025-04-01 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_project_sprint_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='creator_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sprint',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='main.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='creator_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
