# Generated by Django 5.1.5 on 2025-04-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_project_creator_id_sprint_project_team_creator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
