# Generated by Django 5.1.5 on 2025-04-25 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_company_team_user_alter_sprint_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='company',
        ),
    ]
