# Generated by Django 5.1.5 on 2025-04-25 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_team_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='main.company'),
            preserve_default=False,
        ),
    ]
