# Generated by Django 5.1.5 on 2025-04-25 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_team_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='company',
        ),
    ]
