# Generated by Django 5.1.5 on 2025-04-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_team_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='company',
            field=models.IntegerField(default=1),
        ),
    ]
