# Generated by Django 5.1.5 on 2025-04-30 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_team_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_user',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='main.team'),
        ),
    ]
