# Generated by Django 5.1.5 on 2025-04-30 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_team_id_team_user_team'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='team_user',
            unique_together={('team', 'user_id')},
        ),
    ]
