# Generated by Django 5.1.5 on 2025-05-01 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_team_user_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team_user',
            new_name='Project_user',
        ),
        migrations.AddField(
            model_name='project_user',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='main.project'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='project_user',
            unique_together={('project', 'user_id')},
        ),
        migrations.AddField(
            model_name='project',
            name='amount_of_persons',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='main.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='team_leader',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='project_user',
            name='team',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]

