# Generated by Django 5.1.5 on 2025-05-05 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_rename_team_user_project_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='main.company')),
            ],
            options={
                'unique_together': {('company', 'user_id')},
            },
        ),
    ]
